services:
  - type: web
    name: dcp-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node app.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
    rootDir: backend

  - type: web
    name: dcp-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --port $PORT
    envVars:
      - key: VITE_API_URL
        sync: false
    autoDeploy: true
    rootDir: frontend 